apiVersion: v1
kind: Secret
metadata:
  name: spe-secrets
type: Opaque
data:
  email-user: EMAIL_USER_PLACEHOLDER
  email-pass: EMAIL_PASS_PLACEHOLDER
  jwt-secret: c2VjcmV0
  mongo-uri: bW9uZ29kYjovL21vbmdvOjI3MDE3L3NwZV9kYg==
