apiVersion: v1
kind: Secret
metadata:
  name: spe-secrets
type: Opaque
data:
  email-user: c2FydmVzaGt1bWFyYTEyM0BnbWFpbC5jb20=
  email-pass: ZG5oaGF5a3VvdXFjY3BqdQ==
  jwt-secret: c2VjcmV0
  mongo-uri: bW9uZ29kYjovL21vbmdvOjI3MDE3L3NwZV9kYg==
