apiVersion: batch/v1
kind: Job
metadata:
  name: seed-master-job
spec:
  template:
    spec:
      containers:
      - name: seed-master
        image: auth-service:latest
        imagePullPolicy: IfNotPresent
        command: ["node", "seed_master.js"]
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: spe-secrets
              key: mongo-uri
      restartPolicy: OnFailure
  backoffLimit: 4
